"""WHY iter54 and iter56 give different EURUSD numbers.
They are NOT the same measurement. Show it explicitly."""
import json, numpy as np
D=json.load(open('/tmp/m2026.json'))
c=np.array(D['eur']['c'],float)
r=np.zeros(len(c)); r[1:]=np.log(c[1:]/c[:-1])
r=r[1:]
print("="*72)
print("THE TWO REPORTS MEASURE DIFFERENT THINGS")
print("="*72)
print()
print("iter54  : Kraken EURUSD, 1-MINUTE bars, 97 minutes of ONE session")
print("          metric = median |1-min move| / spread  -> 0.58x")
print("          purpose = can a 1-minute strategy pay its spread?")
print()
print("iter56  : Yahoo EURUSD=X, DAILY bars, 150 days of 2026")
print("          metric = straddle P&L priced at 1.25x trailing vol -> -31.17%/mo")
print("          purpose = does the volatility-magnitude model work in 2026?")
print()
print("Different venue, different timeframe, different statistic, different question.")
print("Neither contradicts the other. I should have labelled them clearly.")
print()
print("="*72)
print("DAILY EURUSD 2026 — the scale iter56 actually used")
print("="*72)
print("  median |1-DAY move| : %.2f bp"%(1e4*np.median(np.abs(r))))
print("  mean   |1-DAY move| : %.2f bp"%(1e4*np.abs(r).mean()))
print("  spread (round trip) : 0.30 bp")
print("  DAILY move/spread   : %.1fx   <- vs 0.58x at 1-minute"%(1e4*np.median(np.abs(r))/0.30))
print()
print("So at DAILY frequency EURUSD clears its spread easily (%.0fx)."%(1e4*np.median(np.abs(r))/0.30))
print("The -31.17%/mo in iter56 is NOT a spread problem. It is the straddle")
print("PREMIUM problem: you pay 1.25x trailing vol and realised vol came in lower.")
